In [1]:
import pandas as pd
import numpy as np

In [339]:
df_subgen = pd.read_csv("genero_subgenero.csv") #check
df_multi = pd.read_csv("multimedia.csv") #check
df_usuarios = pd.read_csv("usuarios.csv") #check
df_prove = pd.read_csv("proveedores.csv") #check
df_subs = pd.read_csv("subscripciones.csv")
df_vis = pd.read_csv("visualizaciones.csv")
df_pagos = pd.read_csv("pagos_v2.csv")

In [361]:
# Tabla users se puede usar tal cual
df_subgen
df_gen = df_subgen["genero"].drop_duplicates()
df_subgenero = df_subgen[~df_subgen["nombre_subgenero"].isnull()]
df_gen = df_gen.reset_index()
df_subgenero
df_gen = df_gen["genero"].reset_index().rename({'index':'gid'}, axis=1)

#df_subgenero.join(df_gen, on="genero")
df_gen_subgen = df_gen.set_index('genero').join(df_subgen.set_index('genero'))
df_gen_subgen = df_gen_subgen.reset_index()[["gid","nombre_subgenero"]]
df_gen_subgen = df_gen_subgen[~df_gen_subgen["nombre_subgenero"].isnull()]
#df_gen_subgen.to_csv(folder + "genero_subgenero.csv", index=False)
#df_gen.to_csv("8)genero.csv", index=False)
df_gen_subgen = df_gen_subgen.rename(columns={"nombre_subgenero":"genero"})
df_gen_subgen = df_gen_subgen.merge(df_gen, on="genero", how="inner")
df_gen_subgen = df_gen_subgen.rename(columns={'gid_x': "gid" ,"gid_y":"subgid"})[["gid","subgid"]]
#df_gen_subgen.to_csv("9)subgenero.csv", index=False)

    gid                        genero
0     0                      Thriller
1     1               Ciencia ficción
2     2                      Misterio
3     3                      Familiar
4     4               Fantasía oscura
5     5                        Acción
6     6                         Drama
7     7           Thriller sicológico
8     8                     Biografía
9     9                      Fantasía
10   10            Romance Planetario
11   11                       Biopunk
12   12                       Comedia
13   13  Ciencia ficción apocalíptica
14   14                        Guerra
15   15                      Aventura
16   16                       Deporte
17   17                     Cyberpunk
18   18                     Histórico
19   19                     Animación
20   20                       Slasher
21   21                        Música
22   22                        Horror
23   23                        Crimen
24   24                       Romance

In [233]:
# De la table df_prove se puede encontrar la info de 
df_prove2 = df_prove[["id", "nombre", "costo"]]
df_prove3 = df_prove2.drop_duplicates().sort_values(by="id")
df_prove3 #Esta tabla es equivalente a la que nosotros tenemos
folder = 'ToBDD/'
df_prove3.to_csv(folder + '6)proveedor.csv', index=False)
df_prove3

     id              nombre  costo
10    1             Netflix   4500
17    2  Amazon Prime Video   3700
26    3         Crunchyroll   4400
50    4                HBO+   3500
13    5          Funimation   3900
7     6             Disney+   6500
0     7               Star+   7100
11    8                Hulu   7000
3     9            Showtime   3200
184  10                Stan   7900
1    11             Peackok   4000
8    12                 Viu   5000
32   13            Sony Liv   3100
6    14      Movistar+ Lite   7400
66   15          Discovery+   3700
55   16          Rakuten TV   6500
18   17                 Sky   6400
28   18         ATRESplayer   2800
29   19         Mitele Plus   3700
2    20             DCCanal   4000

In [410]:
# Peliculas pagadas
df_pelipag = df_prove[~df_prove["precio"].isnull()].sort_values(by="id")[["id","costo", "pid","precio","disponibilidad"]].astype({"pid":int})
#df_pelipag.astype({})
df_prove_serie = df_prove[~df_prove["sid"].isnull()][["id","sid"]].sort_values(by="id").astype({"sid":int}) #id_prove e id_serie
df_prove_pelifree = df_prove[~df_prove["pid"].isnull()]
df_peli_incluida = df_prove_pelifree[df_prove_pelifree["precio"].isnull()][["id", "pid"]].sort_values(by="id").astype({"pid":int})
# id_prove, id_peli
df_peli_incluida.to_csv(folder+'3)ofreceenplan.csv', index=False)
#df_prove_serie.to_csv(folder+'2.1)proveedor_serie.csv', index=False)
#df_pelipag = df_pelipag.rename({'id':'pro_id'}, axis=1).sort_values(by="pro_id")[["pro_id","pid","precio","disponibilidad"]].\
#astype({"pid":int})
#df_pelipag.to_csv(folder + '2)ofrece_pagadas.csv', index = False)
df_pelipag.to_csv(folder+"2)ofrece_pagadas.csv", index=False)

In [446]:
# Equivalente a columna la tabla de peliculas
df_peli = df_multi[["pid","titulo","puntuacion","clasificacion","duracion","año"]].drop_duplicates()
df_peli = df_peli[pd.notnull(df_peli["pid"])].sort_values(by="pid").astype({"pid":int})
#df_peli.to_csv(folder + '1)peliculas.csv', index=False)
df_peli.tail(50)

,pid,titulo,puntuacion,clasificacion,duracion,año
22,52,Chasing 3000,9.8,G,115,2010
346,53,Red Tails,5.2,G,125,2012
204,54,Aftermath,3.6,PG-13,84,2013
254,55,The Invited,5.3,G,95,2010
106,56,Something Borrowed,3.2,PG-13,112,2011
340,57,CHIPS,3.6,PG,100,2017
280,58,Ramona and Beezus,5.4,G,104,2010
75,59,Rings,7.3,G,102,2017
45,60,Love & Other Drugs,6.8,PG-13,112,2010
131,61,Syrup,2.6,PG-13,90,2013
407,62,A Thousand Words,5.2,PG-13,91,2012
594,63,The Legend of Secret Pass,8.9,G,92,2010
445,64,Night of the Templar,9.0,PG,101,2013
70,65,What's Your Number?,1.4,G,106,2011
119,66,Jersey Justice,6.3,PG-13,100,2014
225,67,Cell,8.8,PG,98,2016
339,68,Night Catches Us,7.4,PG,90,2010
263,69,Drive,1.1,G,100,2011
395,70,Kid Cannabis,8.9,PG,110,2014
146,71,Santorini Blue,6.7,PG,90,2013
201,72,The Wolfman,4.5,G,103,2010
259,73,The Last Full Measure,9.7,G,116,2019
1,74,The Boxtrolls,1.0,NC-17,96,2014
621,75,The Incredible Burt Wonderstone,4.6,PG,100,2013
562,76,Dallas Buyers Club,4.9,PG,117,2013
163,77,Elliot Loves,1.9,G,92,2012
126,78,Jack Reacher,9.8,G,130,2012
16,79,R.I.P.D.,5.1,PG-13,96,2013
288,80,Miles Ahead,5.6,G,100,2015
184,81,The Yellow Wallpaper,5.3,PG,115,2012
136,82,Scary Movie 5,7.2,PG,88,2013
66,83,13,2.6,PG-13,91,2010
284,84,The Dirt,1.3,PG-13,107,2019
58,85,Thor,10.0,PG,115,2011
114,86,Devil's Knot,8.3,R,114,2013
111,87,It's Kind of a Funny Story,8.1,PG,101,2010
527,88,Jack and Jill,3.0,G,91,2011
118,89,The Do-Deca-Pentathlon,9.4,PG,76,2012
40,90,She's Out of My League,9.6,G,104,2010
218,91,Flipped,6.9,PG-13,90,2010
198,92,Valentine's Day,5.3,PG,125,2010
30,93,The Power of Few,4.5,G,96,2013
459,94,Dreamkiller,8.5,PG-13,110,2010
171,95,Priest,3.8,PG,87,2011
433,96,Maximum Ride,3.9,PG-13,88,2016
442,97,Waking Madison,5.2,G,89,2010
15,98,The Babymakers,6.6,NC-17,95,2012
57,99,Electric Slide,6.7,PG,95,2014
169,100,Krystal,2.0,PG-13,90,2017
428,101,Scream,7.0,NC-17,111,1996

In [420]:
df_serie = df_multi[["sid","cid","serie","titulo","puntuacion","año","clasificacion","genero","numero","duracion"]] 
df_serie = df_serie[pd.notnull(df_serie["sid"])].sort_values(by="sid")
df_serie_final = df_serie[["sid","serie","puntuacion","año","clasificacion","numero"]].drop_duplicates()\
                        .groupby(by=["serie","clasificacion"]).max("numero").reset_index()
df_serie_final = df_serie_final.rename(columns={'numero':'temporadas'})
df_serie_final = df_serie_final[["sid","serie","clasificacion","puntuacion","año","temporadas"]]
df_serie_final = df_serie_final.astype({"sid": int, "temporadas":int}, copy=True)
#df_serie_final.to_csv(folder+'4)series.csv', index=False)
df_serie_final

,sid,serie,clasificacion,puntuacion,año,temporadas
0,11,13 reasons why,R,8.3,2017,3
1,6,31 minutos,G,10.0,2003,4
2,24,Ataque a los titanes,PG-13,9.8,2010,3
3,15,Atypical,PG-13,9.2,2017,3
4,26,Avatar: la leyenda de Aang,G,7.9,2005,3
5,5,Dark,PG-13,9.9,2017,3
6,30,Doctor Who,G,9.0,2005,2
7,16,Dr. House,R,9.3,2004,3
8,2,Friends,PG,9.5,1994,5
9,25,Full Metal Alchemist Brotherhood,PG,8.6,2003,3
10,28,Gossip Girl,PG-13,8.0,2007,3
11,17,Grey's Anatomy,R,8.7,2005,3
12,12,Haikyuu!!,G,10.0,2014,3
13,18,Hora de aventura,G,9.4,2010,3
14,14,Hunter x Hunter,G,7.5,2011,3
15,3,Jojo's Bizarre Adventure,PG,10.0,2012,4
16,7,La Casa de Papel,PG-13,8.0,2017,3
17,21,Los Simpsons,PG-13,9.1,1989,3
18,10,My Hero Academia,G,8.6,2015,3
19,4,Naruto Shippuden,PG-13,9.8,2007,7
20,22,Peaky Blinders,PG,8.6,2013,3
21,23,Rick y Morty,PG,8.3,2013,3
22,13,Riverdale,PG-13,4.3,2017,3
23,31,Scream,NC-17,7.4,2015,2
24,1,Sex Education,R,8.0,2019,2
25,29,Sherlock,PG-13,9.2,2010,3
26,20,Supergirl,G,6.4,2015,3
27,19,Supernatural,PG-13,8.5,2005,3
28,9,The Crown,PG-13,9.5,2016,3
29,27,The Vampire Diaries,PG-13,9.2,2009,3
30,8,Élite,R,5.8,2018,3

In [428]:
df_capitulos = df_serie[["sid","cid","titulo","numero","duracion"]]
df_capitulos = df_capitulos.rename(columns={"titulo": "titulocap", "numero": "temporada"}).astype({"cid":int,"sid":int,"temporada":int})
df_capitulos = df_capitulos.drop_duplicates()
df_capitulos.to_csv(folder+"5)capitulos.csv", index=False)

In [378]:
lista_interes = ["sid", "genero"] #Genero de la serie
df_serie_genero = df_serie[lista_interes].drop_duplicates()
#df_serie_genero.to_csv(folder + 'genero_serie.csv', index=True)
df_serie_genero = df_serie_genero.merge(df_gen, on="genero", how="left")[["sid","gid"]].astype({"sid":int, "gid":"Int64"})
df_serie_genero.to_csv(folder+"11)genero_serie.csv", index = False)
#df_serie_genero.query("sid == 23")
#df_serie_genero2 = df_serie.merge(df_gen, on="genero", how="left")[["sid","gid"]].drop_duplicates()

In [447]:
items_peliculas = ["pid","titulo","duracion","clasificacion","puntuacion"]
items_genero_peli = ["pid", "genero"]
df_peli = df_multi[~df_multi["pid"].isnull()]
#2 tablas: genero_pelicula y peliculas
df_genero_peli = df_peli[items_genero_peli]
df_peli_final = df_peli[items_peliculas]
df_genero_peli = df_genero_peli.sort_values(by="pid")
df_genero_peli = df_genero_peli.merge(df_gen, on="genero", how="left")[["pid","gid"]].astype({"pid":int})
#df_genero_peli.to_csv(folder+"10)genero_pelicula.csv", index=False)
df_genero_peli
df_gen

    gid                        genero
0     0                      Thriller
1     1               Ciencia ficción
2     2                      Misterio
3     3                      Familiar
4     4               Fantasía oscura
5     5                        Acción
6     6                         Drama
7     7           Thriller sicológico
8     8                     Biografía
9     9                      Fantasía
10   10            Romance Planetario
11   11                       Biopunk
12   12                       Comedia
13   13  Ciencia ficción apocalíptica
14   14                        Guerra
15   15                      Aventura
16   16                       Deporte
17   17                     Cyberpunk
18   18                     Histórico
19   19                     Animación
20   20                       Slasher
21   21                        Música
22   22                        Horror
23   23                        Crimen
24   24                       Romance

In [131]:
df_subgen # Queda igual
df_subgen.to_csv(folder + 'genero_subgenero.csv', index=False)

In [296]:
df_pagos
lista_atributos = ["pago_id", "uid", "pid", "pro_id", "fecha"] #no es necesario el monto
lista_atributos_2 = ["pago_id", "uid", "subs_id", "fecha"]
df_registro_peli_paga = df_pagos[~df_pagos["pid"].isnull()][lista_atributos] #Pago peli pagas
df_pago_subs = df_pagos[df_pagos["pid"].isnull()][lista_atributos_2] # pago subscripción
df_registro_peli_paga = df_registro_peli_paga.sort_values(by="pago_id")
df_pago_subs = df_pago_subs.sort_values(by="pago_id")
#df_pago_subs.to_csv(folder+"pago_subscripcion.csv", index=False)
#df_registro_peli_paga.to_csv(folder+".csv", index=False)
#df_registro_peli_paga
#df_pago_subs.sort_values(by="uid")
df_registro_peli_paga = df_registro_peli_paga.sort_values(by="pago_id")
df_registro_peli_paga.to_csv("15)contrata_pelicula.csv", index=False)

In [398]:
lista = ["id","estado","fecha_inicio","pro_id","uid", "fecha_termino"] # id -> id_subscripcion
df_sub = df_subs[lista]
#df_sub.to_csv(folder+"14)subscripcion.csv", index=False)
df_sub = df_sub.sort_values(by="uid")
#df_registro_peli_paga
df_sub

      id     estado fecha_inicio  pro_id  uid fecha_termino
137  377     activa   2020-12-12      13    1           NaN
59   381  cancelada   2020-08-05       8    1    2020-11-26
244  379  cancelada   2021-06-16      14    1    2021-11-19
155  378     activa   2021-10-11       7    1           NaN
72   382  cancelada   2021-11-13      12    1    2021-11-24
..   ...        ...          ...     ...  ...           ...
296  386     activa   2021-06-28       5  142           NaN
373  383  cancelada   2020-08-09      12  142    2020-08-29
29    24  cancelada   2021-05-06       9  146    2021-11-10
176   25     activa   2020-12-28       8  146           NaN
356   26     activa   2020-05-22      16  146           NaN

[419 rows x 6 columns]

In [435]:
df_vis_peli = df_vis[~df_vis["pid"].isnull()][["uid", "pid", "fecha"]].astype({"pid":int})
df_vis_serie = df_vis[~df_vis["cid"].isnull()][["cid","uid","fecha"]].astype({"cid":int})
#df_vis_peli.to_csv(folder+"16)vepelicula.csv", index=False)
#df_vis_serie.to_csv(folder+"17)veserie.csv", index=False)
df_vis_serie

      cid  uid       fecha
1     142   33  2021-12-29
2      87  119  2021-10-13
3      89    5  2021-11-27
4     157  115  2021-05-18
5      93   22  2021-03-30
...   ...  ...         ...
2698  153   25  2021-11-20
2699  105   26  2021-02-07
2700  146   23  2021-05-20
2702  116   43  2021-10-30
2703   92   45  2020-05-16

[1766 rows x 3 columns]

In [389]:
df_usuarios = df_usuarios.rename(columns={"id":"uid"}).sort_values(by="uid").astype({"uid":int})
#df_usuarios.to_csv(folder+"7)usuarios.csv", index=False)
df_usuarios

    uid             nombre                  mail  password       username
69    1   Elizabeth Miller     emiller@gmail.com  oCcUFjmL    emiller1965
84    2  Michelle Williams   mwilliams@gmail.com  W9Sxt1sQ  mwilliams1985
77    3      Sharon Garcia     sgarcia@yahoo.com  6Jb2Rmc6    sgarcia1969
40    4      Lawrence Lowe       llowe@yahoo.com  TYhtqhqs      llowe1987
85    5       Allison West       awest@gmail.com  0os2ByK9      awest1969
..  ...                ...                   ...       ...            ...
24  133         Brian Rios      brios@icloud.com  ow8NkWYm      brios1983
1   134    Joseph Harrison    jharrison@yahoo.es  ZCtisRw5  jharrison1997
89  141     Jessica Taylor     jtaylor@yahoo.com  5f3ioZ9I    jtaylor1997
93  142    Matthew Whitney  mwhitney@hotmail.com  qVYt81JH   mwhitney1991
35  146          John Wade      jwade@icloud.com  ENjqJ0g3      jwade1981

[100 rows x 5 columns]

In [387]:
df_pago_subscripcion = df_pagos[df_pagos["subs_id"].notnull()].sort_values(by="subs_id")[["pago_id","subs_id","fecha"]].astype({"subs_id":int})
df_pago_subscripcion.to_csv(folder+"20)pago_subs.csv", index=False)
df_pago_subscripcion.head()

      pago_id  subs_id       fecha
3356     6370        1  2021-08-08
3514     6371        1  2021-09-08
3814     6369        1  2021-07-08
3787     6368        1  2021-06-08
3551     6379        2  2021-04-27

In [384]:
df_sub = df_subs.rename(columns={"id": "sub_id"})
df_sub_user = df_sub[["sub_id", "uid"]].sort_values(by="sub_id")
df_sub_proveedor = df_sub[["sub_id", "pro_id"]].sort_values(by="sub_id")
df_subscripcion = df_sub[["sub_id", "estado", "fecha_inicio","fecha_termino"]].sort_values(by="sub_id")

df_sub_user.to_csv(folder+"21)subscripcion_user.csv", index=False)
df_sub_proveedor.to_csv(folder+"22)subscripcion_proveedor.csv", index=False)
df_subscripcion.to_csv(folder+"23)subscripcion.csv", index=False)

In [443]:
df_pago_peli = df_pagos[df_pagos["subs_id"].isnull()][["pago_id", "uid","pid", "pro_id", "fecha"]].astype({"pid":int, "pro_id":int})
#df_pago_peli.to_csv(folder+"25)pago_pelicula.csv", index=False)
df_pago_peli

      pago_id  uid  pid  pro_id       fecha
7       10716  106   21       7  2021-12-13
48      10700   64   59       3  2021-05-22
59      10672   17   26       6  2021-08-04
63      10387  141   99       9  2021-03-04
65      10439    9   97      13  2021-11-11
...       ...  ...  ...     ...         ...
4359    10627   46   82      10  2020-11-20
4364    10417   59   79      19  2021-08-11
4367    10396   35   82       7  2021-06-08
4370    10438    9   13      13  2021-11-07
4371    10706  142   21       7  2021-08-21

[379 rows x 5 columns]